### ISSUE TITLE
Good documentation / tutorials

### ISSUE THREAD

**Issue by kartiksura** [splunk/pion#60]
Any links to good documentation or tutorial for starting with pion? Also I would like to know if we can do async long io with this library?

**Comment by DragonOsman** [comment]
I would also like some documentation as well as (more) tutorials.  I need to be able to write code to see how to do stuff with library rather than just reading the documentation, so some actual tutorials to go with the documentation would be great.

By the way (and I'm not sure if it's okay to ask this here), is there any possibility of this library to be included in Boost itself?  I know there's Beast, but I heard it's for low-level HTTP support.  What will we do if we need higher-level support and can't find anything for it in Boost (but want to use Boost)?  Also, we need a library with higher-level HTTP support to be included into the standard library as well.
